### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by SukkoPera** [AwesomeInferno/68000Relocator#1]
What license is this released under?

**Comment by SukkoPera** [comment]
Well, I've forked this and made my own version. If you don't agree, just say so and I'll delete it.

**Comment by Stoobs** [comment]
LGPL3

Hadn't really thought too much about it until now :)

**Comment by SukkoPera** [comment]
Thanks, but the license file you added contains GPL3, not LGPL3 :).

**Comment by Stoobs** [comment]
Well, it's that one then.
